### ISSUE TITLE
packaging for Debian

### ISSUE THREAD

**Issue by trebmuh** [sboukortt/intersect-lv2#1]
Hi @sboukortt .

I've been building master head on a Debian Stretch, and it seems to work (ie: it builds). Now, I'm trying to package it, and I've got an issue. I don't know if you'll be able to help, but hey, no question means I'm sure to get no answer!

So, while using a Debian tool called pbuilder, which is building the package in a chroot, it stops there:

```
make[1]: Entering directory '/build/intersect-lv2-1.2'
tup variant config/release.config
Initializing .tup in /build/intersect-lv2-1.2
.tup repository initialized.
tup warning: unshare(CLONE_NEWUSER) failed, and tup is not privileged. Subprocesses will have '.tup/mnt' paths for the current working directory and some dependencies may be missed.
tup: Added variant 'build-release' using config file 'config/release.config'
make[1]: Leaving directory '/build/intersect-lv2-1.2'
   debian/rules override_dh_auto_build
make[1]: Entering directory '/build/intersect-lv2-1.2'
tup
tup warning: unshare(CLONE_NEWUSER) failed, and tup is not privileged. Subprocesses will have '.tup/mnt' paths for the current working directory and some dependencies may be missed.
[ tup ] [0.067s] Scanning filesystem...
fuse: device not found, try 'modprobe fuse' first
tup error: Timed out waiting for the FUSE file-system to be ready.
tup error: Unable to mount FUSE on .tup/mnt
debian/rules:10: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 1
make[1]: Leaving directory '/build/intersect-lv2-1.2'
debian/rules:4: recipe for target 'build' failed
make: *** [build] Error 2
```

Any idea about what's going on and how to solve it maybe?

**Comment by sboukortt** [comment]
Hi @trebmuh, and thank you for your interest!

It seems that someone has encountered a similar problem in the past while building `tup` itself (https://ubuntuforums.org/showthread.php?t=1884557) but it doesn’t seem like they found a solution (or at least they did not update the thread if they did).

Since `tup` is able to generate a shell script that performs the build, perhaps an acceptable workaround would be to first run `tup generate --config config/release.config build.sh` from outside `pbuilder`, and then run the generated `build.sh` from inside of it?

One caveat is that the generated script will try to run `tup varsed` to generate `manifest.ttl` from `manifest.ttl.in`, which I think will fail. That should be replaced with something along the lines of `sed -e s/@EXT@/so/g .../manifest.ttl.in > .../manifest.ttl` (`@EXT@` is the only variable that needs to be substituted).

If `tup generate` is too much of a hassle to make work, maybe it would be reasonable instead to hardcode the build commands. I think something along these lines should work:

```bash
mkdir -p intersect.lv2
clang src/*.c -shared -o intersect.lv2/intersect.so -O3 -flto -fPIC `pkg-config --cflags --libs lv2 fftw3f` -s
cp metadata/intersect.ttl intersect.lv2/intersect.ttl
sed -e 's/@EXT@/so/g' metadata/manifest.ttl.in > intersect.lv2/manifest.ttl
```

I would be interested in your progress and of course, feel free to ask further questions if you have any :)

Thanks,
Sami

**Comment by trebmuh** [comment]
@sboukortt , thank you for your quick answer. I discarded `tup` and used the build command lines which gave me a working deb package. By "working", I mean that it builds. Now, I'm going to test it a bit before releasing it to the LibraZiK-2's users. I'll keep you updated.

**Comment by trebmuh** [comment]
Hi @sboukortt , I've tested it and it's working great. One of the way I'll use it is when I'm doing music production workshops, I'll use it to "deconstruct" a well known song re R/L balance. That'll give my students a good quick understanding of what a balance is while we'll be working on the mixing steps.

**Comment by sboukortt** [comment]
Great to hear that it’s useful to you! Thank you for the update.
